version: '3.5'

services:
  plantcv_thermal:
    profiles:
      - "dev"
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    environment:
      INPUT_FILE: ${INPUT_FILE}
      COORDS: ${COORDS}
      TEMP: ${TEMP}
    volumes:
      - ./src:/src
      - ./entrypoint.sh:/entrypoint.sh
      - ${RESULTS}:/results
      - ${OUTDIR}:/outdir
      - ${INPUTDIR}:/inputdir
    entrypoint:

      - ./entrypoint.sh

